apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://storage.googleapis.com/chart-packages'
    targetRevision: x
    chart: nasa-app
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
