name: ArgoCD Setup
on:
  workflow_dispatch:

env:
  PROJECT_ID: named-signal-392608

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Get GKE plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials main-cluster --region us-central1-a

      - name: Create initial namesapces
        run: |
          kubectl create namespace test
          kubectl create namespace app

      - name: Inatall ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: Access ArgoCD in external IP
        run: |
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

      - name: Install ArgoCD-cli
        run: |
          curl -L -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Apply ArgoCD Applications manifests
        run: |
          kubectl apply -f argocd/test.yaml -n argocd
          kubectl apply -f argocd/prod.yaml -n argocd

      - name: Get password for 'admin'
        run: |
          sleep 15
          argocd admin initial-password -n argocd
