name: CI and Test
on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

env:
  PROJECT_ID: named-signal-392608
  BUCKET_NAME: chart-packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker Env
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > ./app/.env

      - name: Define TAG and HELM_PACKAGE
        run: |
          TAG=$(bash versioning.sh)
          HELM_PACKAGE=nasa-app-${TAG}.tgz
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "HELM_PACKAGE=${HELM_PACKAGE}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gha-pipeline:${{ env.TAG }}

      - name: Create Helm Chart files
        run: |
          echo "apiVersion: v2" > ./chart/Chart.yaml
          echo "name: nasa-app" >> ./chart/Chart.yaml
          echo "version: ${{ env.TAG }}" >> ./chart/Chart.yaml
          echo "description: A Helm chart for deploying Flask and Redis" >> ./chart/Chart.yaml
          echo "TAG: ${{ env.TAG }}" > ./chart/values.yaml

      - name: Package Helm Chart
        run: |
          helm package ./chart

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Upload Helm Chart to GCP
        run: |
          helm plugin install https://github.com/hayorov/helm-gcs.git
          helm gcs init gs://chart-packages
          helm repo add nasa-app gs://chart-packages
          helm gcs push ${{ env.HELM_PACKAGE }} nasa-app --public

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define TAG and HELM_PACKAGE
        run: |
          TAG=$(bash versioning.sh --no-rename)
          HELM_PACKAGE=nasa-app-${TAG}.tgz
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "HELM_PACKAGE=${HELM_PACKAGE}" >> $GITHUB_ENV

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Get GKE plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials test-cluster --region us-central1-a

      - name: Download Helm chart from GCP bucket
        run: |
          gsutil cp gs://${{ env.BUCKET_NAME }}/${{ env.HELM_PACKAGE }} .

      - name: Deploy Helm chart
        run: |
          helm upgrade --install nasa-app ${{ env.HELM_PACKAGE }}

      - name: Run Helm Tests
        run: |
          helm test nasa-app || (curl -X POST https://us-central1-named-signal-392608.cloudfunctions.net/mark_failures && exit 1)
