name: Post Deployment
on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

env:
  PROJECT_ID: named-signal-392608

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Get GKE plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials main-cluster --region us-central1-a

      - name: Check and Install Prometheus and Grafana
        run: |
          if helm list -n monitoring | grep -q "prometheus"; then
            echo "Prometheus is already installed."
          else
            kubectl create namespace monitoring
            helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
            helm repo update
            helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring \
              --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
              --set prometheus.prometheusSpec.serviceMonitorNamespaceSelector.matchNames=app
            kubectl patch svc prometheus-grafana -n monitoring -p '{"spec": {"type": "LoadBalancer"}}'
            echo "Prometheus installed."
          fi

  cleanups:
    runs-on: ubuntu-latest

    steps:
      - name: Clean failed packages if there are more than 5
        run: |
          curl https://us-central1-named-signal-392608.cloudfunctions.net/failures_handling

      - name: Clean Bucket packages if there are more than 20
        run: |
          curl https://us-central1-named-signal-392608.cloudfunctions.net/bucket_handling

      - name: Clean images in DockerHub if there are more than 20
        run: |
          curl https://us-central1-named-signal-392608.cloudfunctions.net/docker_registry_handling